___
# Hackerrank Magic Square Problem
### A Magic Square is:
1. An nxn square matrix
2. That contains integers in the form 1,2,3,...,n**2
2. Whose rows, columns and diagonals sum to the same number
#### Below is the classic 3X3 Magic Square:
![](Magicsquareexample.png)
___

___
### You derive the classic Magic Square above using 5 in the center, and different additions and subractions of 5 around the center:
* [5-3, 5+2, 5+1] in the first row
* [5+4, 5+0, 5-4] in the second row
* [5-1, 5-2, 5+3] in the third row
___

___
### You can further derive seven other Magic Squares from the *C*lassic *M*agic *S*quare above (*CMS*), by:
1. Flipping row 1 and row 3 of CMS (```numpy.flip(cms,0)```)
2. Flipping column 1 and column 3 of CMS (```numpy.flip(cms,1)```)
3. Flipping row 1 and row 3 of the flipped CMS matrix in number 2 (```numpy.flip(m2,0)```)
4. Transposing CMS (```cms.T```)
5. Flipping row 1 and row 3 of the transposed CMS (```numpy.flip(cms.T,0)```)
6. Flipping column 1 and column 3 of ther transposed CMS (```numpy.flip(cms.T,1)```)
7. Flipping row 1 and row 3 of the flipped transposed CMS matrix in number 6(```numpy.flip(m6,0)```)

___

___
### In a "sane" world, you would create these matrices using numpy
___

In [1]:
import numpy as np
cms = np.array([[5-3, 5+2, 5+1],[5+4, 5+0, 5-4] ,[5-1, 5-2, 5+3]])
m1 = np.flip(cms,0)
m2 = np.flip(cms,1)
m3 = np.flip(m2,0)
m4 = cms.T
m5 = np.flip(m4,0)
m6 = np.flip(m4,1)
m7 = np.flip(m6,0)

In [2]:
cms,m1,m2,m3,m4,m5,m6,m7

(array([[2, 7, 6],
        [9, 5, 1],
        [4, 3, 8]]),
 array([[4, 3, 8],
        [9, 5, 1],
        [2, 7, 6]]),
 array([[6, 7, 2],
        [1, 5, 9],
        [8, 3, 4]]),
 array([[8, 3, 4],
        [1, 5, 9],
        [6, 7, 2]]),
 array([[2, 9, 4],
        [7, 5, 3],
        [6, 1, 8]]),
 array([[6, 1, 8],
        [7, 5, 3],
        [2, 9, 4]]),
 array([[4, 9, 2],
        [3, 5, 7],
        [8, 1, 6]]),
 array([[8, 1, 6],
        [3, 5, 7],
        [4, 9, 2]]))

___
### You solve the Hackerrank problem by:
1. element-wise subtracting each of the 8 matrices above with the matrix that you are presented in the problem
2. for each subtracted matrix, convert the subtracted values to absolute values
3. for each subtracted-absolute-values matrix, sum all of the elements
4. The solution is the minimum of those 8 values
___

In [3]:
# let s0 be an example problem from Hackerrank
s0 = np.array([[5,3,4],[1, 5, 8],[6, 4, 2]])
step1 = [s0-m for m in [cms,m1,m2,m3,m4,m5,m6,m7]]
step2 = [np.absolute(m) for m in step1]
step3 = [m.reshape(-1).sum() for m in step2]
final_answer = min(step3)
print(f'The final_answer is {final_answer}')

The final_answer is 7


___
# Hackerrank is not a sane world.  You can't use numpy.
So the cells below use regular python to create the 8 matrices, and then create the solution.
___

In [4]:
import math
import os
import random
import re
import sys


In [5]:
def atran(s):
    # transpose
    il = len(s)
    st = [[s[j][i] for j in range(len(s[i]))] for i in range(il)]
    return st

def aud(s):
    si_last = len(s) - 1
    sc = s.copy()
    sc[0] = s[si_last]
    sc[si_last] = s[0]
    return sc

def alr(s):
    il = len(s)
    st = [[s[i][j] for j in range(len(s[i])-1,-1,-1)] for i in range(il)]
    return st

def audalr(s):
    return alr(aud(s))

def adiff(s1,s2):
    return [[s1[i][j] - s2[i][j] for j in range(len(s1[i]))] for i in range(len(s1))]

def absadiff(s1,s2):
    ad = adiff(s1,s2)
    return [[abs(ad[i][j]) for j in range(len(ad[i]))] for i in range(len(ad))]

def sumabsadiff(s1,s2):
    return sum(aflat(absadiff(s1,s2)))

def arrdiff(s1,s2):
    # elementwise abs diff
    return [[s1[i][j] - s2[i][j] for j in range(len(s1[i]))] for i in range(len(s1))]

def aflat(s):
    return [s[i][j] for i in range(len(s)) for j in range(len(s[i]))]
    
def mags():
    # classic magic square
    m = [[5-3, 5+2, 5+1],[5+4, 5+0, 5-4] ,[5-1, 5-2, 5+3]]
    maud = aud(m)
    malr = alr(m)
    maudalr = audalr(m)
    mt = atran(m)
    mtaud = aud(atran(m))
    mtalr = alr(atran(m))
    mtaudalr = audalr(atran(m))
    return [m, maud,malr,maudalr,mt,mtaud,mtalr,mtaudalr]

def forming_magic_square_solution(s):
    return min([sumabsadiff(s,m) for m in mags()])
    

___
### Use the above methods to solve the Hackerrank problem
___

In [8]:
# example problem matrix
s0 = [
[5,3,4],
[1, 5, 8],
[6, 4, 2]
]


In [9]:
# The solution
forming_magic_square_solution(s0)

7